control '1_10' do
  title 'Ensure user auth tokens rotate within 90 days or less'

  desc <<~DESC
    Auth tokens are authentication tokens generated by Oracle. You use auth tokens to
    authenticate with APIs that do not support the Oracle Cloud Infrastructure signature-based
    authentication. If the service requires an auth token, the service-specific documentation
    instructs you to generate one and how to use it. It is important to secure and rotate an
    auth token every 90 days or less as it provides the same level of access to APIs that do
    not support the OCI signature-based authentication as the user associated to it.
  DESC

  desc 'check', <<~CHECK
    From Console: Login to OCI Console. Select Identity & Security from the Services menu.
    
    Select Domains from the Identity menu. For each domain listed, click on the name and
    select Users . Click on an individual user under the Username heading. Click on Auth
    Tokens in the lower left-hand corner of the page. Ensure the date of the Auth Token under
    the Created column of the Customer Secret Key is no more than 90 days old.
  CHECK

  desc 'fix', <<~FIX
    From Console: Login to OCI Console. Select Identity & Security from the Services menu.
    
    Select Domains from the Identity menu. For each domain listed, click on the name and
    select Users . Click on an individual user under the Username heading. Click on Auth
    Tokens in the lower left-hand corner of the page. Delete any auth token with a date older
    than 90 days under the Created column of the Customer Secret Keys.
  FIX

  impact 0.5

  tag check_id: 'C-1_10'
  tag severity: 'medium'
  tag gid: 'CIS-1_10'
  tag rid: 'xccdf_cis_cis_rule_1_10'
  tag stig_id: '1.1'
  tag gtitle: '<GroupDescription></GroupDescription>'
  tag 'documentable'

  tag cci: [
    'CCI-000364',
    'CCI-000365',
    'CCI-000366',
    'CCI-000421',
    'CCI-001097',
    'CCI-001098',
    'CCI-002395',
    'CCI-002110',
    'CCI-002111',
    'CCI-002112',
    'CCI-000012',
    'CCI-000200',
    'CCI-000199',
    'CCI-000205',
    'CCI-000204'
  ]

  tag nist: [
    'CM-6 a',
    'CM-6 a',
    'CM-6 b',
    'CM-9 a',
    'SC-7 a',
    'SC-7 c',
    'SC-7 b',
    'AC-2 a',
    'AC-2 a',
    'AC-2 b',
    'AC-2 j',
    'IA-5 (1) (e)',
    'IA-5 (1) (d)',
    'IA-5 (1) (a)',
    'IA-5 (8)'
  ]
end
